version: "3.7"
services:
  meshnet:
    image: ghcr.io/mattstechinfo/meshnet:v3.17.0
    networks:
      app-meshnet:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: .env
    hostname: meshnet
    # This command setup redirects traffic to the morphic container, then proceeds with the original meshnet startup sequence.
    command: >
      /bin/sh -c "
      iptables -t nat -A PREROUTING -p tcp --dport 3000 -j DNAT --to-destination 172.40.0.3:3000 &&
      iptables -t nat -A POSTROUTING -j MASQUERADE &&
      nordvpn_login && meshnet_config && meshnet_watch
      "

  # If this fails then you need to build the container first `docker build . -t morphic-morphic --no-cache`
  morphic:
    image: morphic-morphic:latest
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      app-meshnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - meshnet

networks:
  app-meshnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
